using Content.Shared.HL2RP.Contracts.UI;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.HL2RP.Contracts.UI;

[GenerateTypedNameReferences]
public sealed partial class ContractsTerminalWindow : DefaultWindow
{
    private List<ContractListEntry> _contracts = new();
    private int _selectedIndex = -1;
    private bool _suppressSelection;

    public Action<string>? OnAccept;
    public Action? OnCancel;

    public ContractsTerminalWindow()
    {
        RobustXamlLoader.Load(this);

        ContractsList.OnItemSelected += args =>
        {
            if (_suppressSelection)
                return;
            _selectedIndex = args.ItemIndex;
        };

        AcceptButton.OnPressed += _ =>
        {
            if (_selectedIndex < 0 || _selectedIndex >= _contracts.Count)
                return;

            OnAccept?.Invoke(_contracts[_selectedIndex].Id);
        };

        CancelButton.OnPressed += _ => OnCancel?.Invoke();
    }

    public void UpdateState(ContractsTerminalBoundUiState state)
    {
        InsertCardHint.Visible = !state.HasCard;
        CardInfoBox.Visible = state.HasCard;
        LpLabel.Text = $"LP: {state.CardLp}";
        TokensLabel.Text = $"Токены: {state.CardTokens}";

        _contracts = state.Contracts;
        _suppressSelection = true;
        ContractsList.Clear();
        for (var i = 0; i < _contracts.Count; i++)
        {
            var c = _contracts[i];
            ContractsList.AddItem($"{c.Title} ({c.RequiredCount})  +{c.RewardLp} LP, +{c.RewardTokens} токенов");
        }
        _suppressSelection = false;

        var hasActive = !string.IsNullOrWhiteSpace(state.ActiveContractId);
        ActiveBox.Visible = hasActive;
        AcceptButton.Disabled = hasActive;

        if (!hasActive)
            return;

        ActiveTitleLabel.Text = $"Активный контракт: {state.ActiveContractTitle ?? state.ActiveContractId}";
        ActiveProgressLabel.Text = $"Прогресс: {state.ActiveProgress}/{state.ActiveRequired}";
        CancelWarningLabel.Text = $"Отмена контракта до выполнения влечет штраф: -{state.CancelPenaltyLp} LP и -{state.CancelPenaltyTokens} токенов.";
        CancelButton.Text = $"Отменить (штраф -{state.CancelPenaltyLp} LP, -{state.CancelPenaltyTokens} токенов)";
    }
}

