using Content.Shared.HL2RP.Denunciations.UI;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client.HL2RP.Denunciations.UI;

[GenerateTypedNameReferences]
public sealed partial class DenunciationsTerminalWindow : DefaultWindow
{
    private const int MaxReasonLength = 512;
    private List<DenunciationCitizenEntry> _citizens = new();
    private DenunciationCitizenEntry? _selectedCitizen;
    private bool _suppressSelection;

    public Action<NetEntity>? OnSelectCitizen;
    public Action<NetEntity, string, int>? OnSubmitDenunciation;

    public DenunciationsTerminalWindow()
    {
        RobustXamlLoader.Load(this);

        CitizensList.OnItemSelected += args =>
        {
            if (_suppressSelection)
                return;
            if (args.ItemIndex < 0 || args.ItemIndex >= _citizens.Count)
                return;

            OnSelectCitizen?.Invoke(_citizens[args.ItemIndex].CardUid);
        };

        BackToListButton.OnPressed += _ => SetDetailsVisible(false);
        SubmitButton.OnPressed += _ => TrySubmit();

        ReasonTextEdit.OnTextChanged += _ => EnsureReasonAndButtons();
        SeveritySlider.OnValueChanged += _ => SeverityLabel.Text = $"Тяжесть: {GetSeverity()}";
    }

    public void UpdateState(DenunciationsTerminalBoundUiState state)
    {
        ReporterLabel.Text = $"CID отправителя: {state.ReporterCNumber}";
        NoCidHintLabel.Visible = !state.HasReporterCid;

        _citizens = state.Citizens;
        _selectedCitizen = state.SelectedCitizen;
        _suppressSelection = true;
        CitizensList.Clear();
        for (var i = 0; i < _citizens.Count; i++)
        {
            var citizen = _citizens[i];
            var item = CitizensList.AddItem($"{citizen.Name} {citizen.Surname} [{citizen.CNumber}]");
            item.Selected = _selectedCitizen != null && _selectedCitizen.CardUid == citizen.CardUid;
        }
        _suppressSelection = false;

        if (_selectedCitizen == null)
        {
            SetDetailsVisible(false);
            return;
        }

        SetDetailsVisible(true);
        TargetNameLabel.Text = $"Имя: {_selectedCitizen.Name}";
        TargetSurnameLabel.Text = $"Фамилия: {_selectedCitizen.Surname}";
        TargetCodeLabel.Text = $"Код гражданина: {_selectedCitizen.CNumber}";
        EnsureReasonAndButtons();
    }

    private void SetDetailsVisible(bool visible)
    {
        ListView.Visible = !visible;
        DetailsView.Visible = visible;
    }

    private void EnsureReasonAndButtons()
    {
        var reason = Rope.Collapse(ReasonTextEdit.TextRope);
        var visualLength = Math.Min(reason.Length, MaxReasonLength);
        ReasonLengthLabel.Text = $"{visualLength} / {MaxReasonLength}";
        SubmitButton.Disabled = _selectedCitizen == null ||
                                string.IsNullOrWhiteSpace(reason) ||
                                reason.Length > MaxReasonLength;
    }

    private int GetSeverity()
    {
        return Math.Clamp((int) MathF.Round(SeveritySlider.Value), 1, 5);
    }

    private void TrySubmit()
    {
        if (_selectedCitizen == null)
            return;

        var reason = Rope.Collapse(ReasonTextEdit.TextRope).Trim();
        if (string.IsNullOrWhiteSpace(reason))
            return;

        if (reason.Length > MaxReasonLength)
            reason = reason[..MaxReasonLength];

        OnSubmitDenunciation?.Invoke(_selectedCitizen.CardUid, reason, GetSeverity());
        ReasonTextEdit.TextRope = Rope.Leaf.Empty;
        EnsureReasonAndButtons();
    }
}
