using Content.Shared.HL2RP.CID.UI;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.HL2RP.CID.UI;

[GenerateTypedNameReferences]
public sealed partial class CIDTabletWindow : BaseWindow
{
    private List<CIDDatabaseRecord> _records = new();
    private CIDRecordDetails? _selected;

    public Action? OnGenerateNumber;
    public Action<string, string, string>? OnWriteCard;
    public Action<NetEntity>? OnSelectRecord;
    public Action<NetEntity, int>? OnChangeRecordLp;

    public CIDTabletWindow()
    {
        RobustXamlLoader.Load(this);

        Tabs.SetTabTitle(0, "Информация");
        Tabs.SetTabTitle(1, "База данных");
        Tabs.SetTabTitle(2, "Выдача");

        CloseButton.OnPressed += _ => Close();
        GenerateNumberButton.OnPressed += _ => OnGenerateNumber?.Invoke();
        WriteCardButton.OnPressed += _ =>
            OnWriteCard?.Invoke(IssueNameLine.Text, IssueSurnameLine.Text, IssueNumberLine.Text);

        SetLpButton.OnPressed += _ =>
        {
            if (_selected == null || !int.TryParse(SetLpLine.Text, out var lp))
                return;

            OnChangeRecordLp?.Invoke(_selected.CardUid, lp);
        };

        RecordsList.OnItemSelected += args =>
        {
            if (args.ItemIndex < 0 || args.ItemIndex >= _records.Count)
                return;

            OnSelectRecord?.Invoke(_records[args.ItemIndex].CardUid);
        };
    }

    public void UpdateState(CIDTabletBoundUiState state)
    {
        InfoNameLabel.Text = $"Имя: {state.Name}";
        InfoSurnameLabel.Text = $"Фамилия: {state.Surname}";
        InfoNumberLabel.Text = $"Номер гражданина: {state.CNumber}";
        InfoLpLabel.Text = $"LP: {state.LPCount}";
        InfoJobLabel.Text = $"Должность: {state.Job}";

        Tabs.SetTabVisible(2, state.CanIssue);
        IssueStatusLabel.Text = state.HasIssueCard
            ? "Карта для выдачи вставлена"
            : "Вставьте пустую CID карту в слот выдачи";

        SetLpButton.Disabled = !state.CanViewDetails || state.SelectedRecord == null;
        SetLpLine.Editable = state.CanViewDetails;

        UpdateRecords(state.Records);
        UpdateDetails(state.SelectedRecord, state.CanViewDetails);
    }

    private void UpdateRecords(List<CIDDatabaseRecord> records)
    {
        _records = records;
        RecordsList.Clear();
        foreach (var record in records)
        {
            RecordsList.AddItem($"{record.Name} {record.Surname} [{record.CNumber}]");
        }
    }

    private void UpdateDetails(CIDRecordDetails? details, bool canViewDetails)
    {
        _selected = details;
        if (!canViewDetails || details == null)
        {
            DetailsHeader.Text = canViewDetails ? "Выберите запись" : "Недостаточно доступа";
            DetailsNameLabel.Text = "Имя: -";
            DetailsSurnameLabel.Text = "Фамилия: -";
            DetailsNumberLabel.Text = "Номер: -";
            DetailsLpLabel.Text = "LP: -";
            DetailsLevelLabel.Text = "LP уровень: -";
            DetailsTokensLabel.Text = "Токены: -";
            DetailsJobLabel.Text = "Должность: -";
            DetailsAccessLabel.Text = "Access: -";
            return;
        }

        DetailsHeader.Text = "Полная информация";
        DetailsNameLabel.Text = $"Имя: {details.Name}";
        DetailsSurnameLabel.Text = $"Фамилия: {details.Surname}";
        DetailsNumberLabel.Text = $"Номер: {details.CNumber}";
        DetailsLpLabel.Text = $"LP: {details.LPCount}";
        DetailsLevelLabel.Text = $"LP уровень: {details.LPLevel}";
        DetailsTokensLabel.Text = $"Токены: {details.TokensCount}";
        DetailsJobLabel.Text = $"Должность: {details.Job}";
        DetailsAccessLabel.Text = $"Access: {details.Access}";
    }
}
