using Content.Shared.HL2RP.CID;
using Content.Shared.HL2RP.CID.UI;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.HL2RP.CID.UI;

[GenerateTypedNameReferences]
public sealed partial class CIDTabletWindow : DefaultWindow
{
    private List<CIDDatabaseRecord> _records = new();
    private List<CIDDenunciationListEntry> _denunciations = new();
    private CIDRecordDetails? _selectedRecord;
    private CIDDenunciationDetails? _selectedDenunciation;
    private bool _suppressSelectionEvents;
    private bool _suppressDenunciationSelectionEvents;

    public Action? OnGenerateNumber;
    public Action<string, string, string>? OnWriteCard;
    public Action<NetEntity>? OnSelectRecord;
    public Action? OnBackToRecords;
    public Action<NetEntity, int>? OnChangeRecordLp;
    public Action<int>? OnSelectDenunciation;
    public Action? OnBackToDenunciations;
    public Action<int>? OnTakeDenunciation;
    public Action<int>? OnCancelDenunciationResolution;
    public Action<int>? OnAcceptDenunciation;
    public Action<int>? OnRejectDenunciation;
    public Action<NetEntity, string>? OnChangeCitizenJob;

    public CIDTabletWindow()
    {
        RobustXamlLoader.Load(this);

        Tabs.SetTabTitle(0, "Информация");
        Tabs.SetTabTitle(1, "База данных");
        Tabs.SetTabTitle(2, "Выдача");
        Tabs.SetTabTitle(3, "Доносы");

        GenerateNumberButton.OnPressed += _ => OnGenerateNumber?.Invoke();
        WriteCardButton.OnPressed += _ =>
            OnWriteCard?.Invoke(IssueNameLine.Text, IssueSurnameLine.Text, IssueNumberLine.Text);
        ApplyLpButton.OnPressed += _ => TryApplySelectedLp();
        BackToRecordsButton.OnPressed += _ => OnBackToRecords?.Invoke();
        BackToDenunciationsButton.OnPressed += _ => OnBackToDenunciations?.Invoke();
        TakeReportButton.OnPressed += _ => TryTakeDenunciation();
        CancelResolutionButton.OnPressed += _ => TryCancelResolution();
        AcceptReportButton.OnPressed += _ => TryAcceptDenunciation();
        RejectReportButton.OnPressed += _ => TryRejectDenunciation();
        ApplyJobChangeButton.OnPressed += _ => TryApplyJobChange();

        RecordsList.OnItemSelected += args =>
        {
            if (_suppressSelectionEvents)
                return;

            if (args.ItemIndex < 0 || args.ItemIndex >= _records.Count)
                return;

            OnSelectRecord?.Invoke(_records[args.ItemIndex].CardUid);
        };

        DenunciationsList.OnItemSelected += args =>
        {
            if (_suppressDenunciationSelectionEvents)
                return;

            if (args.ItemIndex < 0 || args.ItemIndex >= _denunciations.Count)
                return;

            OnSelectDenunciation?.Invoke(_denunciations[args.ItemIndex].Id);
        };
    }

    public void UpdateState(CIDTabletBoundUiState state)
    {
        InfoNameLabel.Text = $"Имя: {state.Name}";
        InfoSurnameLabel.Text = $"Фамилия: {state.Surname}";
        InfoNumberLabel.Text = $"Номер гражданина: {state.CNumber}";
        InfoLpLabel.Text = $"LP: {state.LPCount}";
        InfoTokensLabel.Text = $"Токены: {state.TokensCount}";
        InfoJobLabel.Text = $"Должность: {state.Job}";

        Tabs.SetTabVisible(2, state.CanIssueCards);
        Tabs.SetTabVisible(3, state.CanUseDenunciations);
        IssueStatusLabel.Text = state.HasIssueCard
            ? "Карта для выдачи вставлена"
            : "Вставьте пустую CID карту в слот выдачи";

        if (!string.IsNullOrWhiteSpace(state.GeneratedNumber))
            IssueNumberLine.Text = state.GeneratedNumber;

        UpdateRecords(state.Records);
        UpdateSelectedRecord(state.SelectedRecord, state.CanViewExtendedCitizenInfo, state.CanEditLoyaltyPoints, state.JobChangeOptions);
        UpdateDenunciations(state.Denunciations);
        UpdateSelectedDenunciation(state.SelectedDenunciation);
    }

    private void UpdateRecords(List<CIDDatabaseRecord> records)
    {
        _records = records;
        _suppressSelectionEvents = true;
        RecordsList.Clear();
        for (var i = 0; i < records.Count; i++)
        {
            var record = records[i];
            var item = RecordsList.AddItem($"{record.Name} {record.Surname} [{record.CNumber}]");
            item.Selected = _selectedRecord != null && _selectedRecord.CardUid == record.CardUid;
        }

        _suppressSelectionEvents = false;
    }

    private void UpdateSelectedRecord(CIDRecordDetails? details, bool canViewExtendedCitizenInfo, bool canEditLoyaltyPoints, List<CIDJobPickerEntry> jobChangeOptions)
    {
        _selectedRecord = details;
        DatabaseListView.Visible = details == null;
        DatabaseDetailsView.Visible = details != null;

        SelectedNameLabel.Text = $"Имя: {details?.Name ?? "-"}";
        SelectedSurnameLabel.Text = $"Фамилия: {details?.Surname ?? "-"}";
        SelectedNumberLabel.Text = $"Номер: {details?.CNumber ?? "-"}";
        SelectedLevelLabel.Text = $"LP уровень: {(details?.LPLevel.ToString() ?? "-")}";
        SelectedTokensLabel.Text = $"Токены: {(details?.TokensCount.ToString() ?? "-")}";
        SelectedJobLabel.Text = $"Должность: {details?.Job ?? "-"}";
        SelectedAccessLabel.Text = $"Права планшета: {FormatTabletPermissions(details?.TabletPermissions)}";

        var canEditLp = canViewExtendedCitizenInfo && canEditLoyaltyPoints && details != null;
        SelectedLpEdit.Editable = canEditLp;
        ApplyLpButton.Disabled = !canEditLp;

        UpdateJobChangeRow(details, jobChangeOptions);

        if (details == null)
        {
            SelectedLpEdit.Text = string.Empty;
            return;
        }

        // Don't overwrite value while user is actively typing.
        if (!SelectedLpEdit.HasKeyboardFocus())
            SelectedLpEdit.Text = details.LPCount.ToString();
    }

    private void UpdateJobChangeRow(CIDRecordDetails? details, List<CIDJobPickerEntry> jobChangeOptions)
    {
        var show = details != null && jobChangeOptions.Count > 0;
        JobChangeRow.Visible = show;
        JobChangeOptionButton.Clear();
        if (!show)
        {
            ApplyJobChangeButton.Disabled = true;
            return;
        }

        foreach (var opt in jobChangeOptions)
        {
            var idx = JobChangeOptionButton.ItemCount;
            JobChangeOptionButton.AddItem(opt.DisplayTitle);
            JobChangeOptionButton.SetItemMetadata(idx, opt.JobPrototypeId);
        }

        ApplyJobChangeButton.Disabled = JobChangeOptionButton.ItemCount == 0;
        if (JobChangeOptionButton.ItemCount > 0)
            JobChangeOptionButton.TrySelect(0);
    }

    private void TryApplyJobChange()
    {
        if (_selectedRecord == null || JobChangeOptionButton.ItemCount == 0)
            return;

        if (JobChangeOptionButton.SelectedMetadata is not string jobProtoId || string.IsNullOrEmpty(jobProtoId))
            return;

        OnChangeCitizenJob?.Invoke(_selectedRecord.CardUid, jobProtoId);
    }
    
    private void TryApplySelectedLp()
    {
        if (_selectedRecord == null)
            return;

        if (int.TryParse(SelectedLpEdit.Text, out var lp))
            OnChangeRecordLp?.Invoke(_selectedRecord.CardUid, lp);
    }

    private void UpdateDenunciations(List<CIDDenunciationListEntry> denunciations)
    {
        _denunciations = denunciations;
        _suppressDenunciationSelectionEvents = true;
        DenunciationsList.Clear();
        for (var i = 0; i < denunciations.Count; i++)
        {
            var report = denunciations[i];
            var item = DenunciationsList.AddItem(
                $"{report.TargetName} {report.TargetSurname} [{report.TargetCNumber}] ({report.Severity} степень)");
            item.Selected = _selectedDenunciation != null && _selectedDenunciation.Id == report.Id;
        }

        _suppressDenunciationSelectionEvents = false;
    }

    private void UpdateSelectedDenunciation(CIDDenunciationDetails? details)
    {
        _selectedDenunciation = details;
        ReportsListView.Visible = details == null;
        ReportsDetailsView.Visible = details != null;

        if (details == null)
        {
            ReportTargetLabel.Text = "На кого: -";
            ReportReporterLabel.Text = "Кто подал: -";
            ReportSeverityLabel.Text = "Тяжесть: -";
            ReportResolverLabel.Text = "Разбирает: -";
            ReportReasonLabel.SetMessage(string.Empty);
            TakeReportButton.Disabled = true;
            ReportControlButtons.Visible = false;
            return;
        }

        ReportTargetLabel.Text = $"На кого: {details.TargetName} {details.TargetSurname} [{details.TargetCNumber}]";
        ReportReporterLabel.Text = $"Кто подал: {details.ReporterName} {details.ReporterSurname} [{details.ReporterCNumber}]";
        ReportSeverityLabel.Text = $"Тяжесть: {details.Severity} степень";
        ReportResolverLabel.Text = details.ResolverName == null
            ? "Разбирает: никто"
            : $"Разбирает: {details.ResolverName} {details.ResolverSurname} [{details.ResolverCNumber}]";
        ReportReasonLabel.SetMessage(details.Reason);

        TakeReportButton.Disabled = !details.CanTake;
        ReportControlButtons.Visible = details.CanControlResolution;
    }

    private void TryTakeDenunciation()
    {
        if (_selectedDenunciation == null)
            return;

        OnTakeDenunciation?.Invoke(_selectedDenunciation.Id);
    }

    private void TryCancelResolution()
    {
        if (_selectedDenunciation == null)
            return;

        OnCancelDenunciationResolution?.Invoke(_selectedDenunciation.Id);
    }

    private void TryAcceptDenunciation()
    {
        if (_selectedDenunciation == null)
            return;

        OnAcceptDenunciation?.Invoke(_selectedDenunciation.Id);
    }

    private void TryRejectDenunciation()
    {
        if (_selectedDenunciation == null)
            return;

        OnRejectDenunciation?.Invoke(_selectedDenunciation.Id);
    }

    private static string FormatTabletPermissions(CidTabletPermissions? permissions)
    {
        if (permissions is not { } p || p == CidTabletPermissions.None)
            return "нет";

        var parts = new List<string>();
        if (p.HasFlag(CidTabletPermissions.IssueCards))
            parts.Add("выдача карт");
        if (p.HasFlag(CidTabletPermissions.ViewExtendedCitizenInfo))
            parts.Add("расширенные данные");
        if (p.HasFlag(CidTabletPermissions.EditLoyaltyPoints))
            parts.Add("изменение LP");
        if (p.HasFlag(CidTabletPermissions.Denunciations))
            parts.Add("доносы");
        if (p.HasFlag(CidTabletPermissions.ChangeJobDepartment))
            parts.Add("смена должности (департамент)");
        if (p.HasFlag(CidTabletPermissions.ChangeJob))
            parts.Add("смена должности (все)");

        return string.Join(", ", parts);
    }
}
