using Content.Shared.HL2RP.CID.UI;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.HL2RP.CID.UI;

[GenerateTypedNameReferences]
public sealed partial class CIDTabletWindow : BaseWindow
{
    private List<CIDDatabaseRecord> _records = new();
    private CIDRecordDetails? _selectedRecord;
    private bool _suppressSelectionEvents;

    public Action? OnGenerateNumber;
    public Action<string, string, string>? OnWriteCard;
    public Action<NetEntity>? OnSelectRecord;
    public Action<NetEntity, int>? OnChangeRecordLp;

    public CIDTabletWindow()
    {
        RobustXamlLoader.Load(this);

        Tabs.SetTabTitle(0, "Информация");
        Tabs.SetTabTitle(1, "База данных");
        Tabs.SetTabTitle(2, "Выдача");
        Title = "CID планшет";

        GenerateNumberButton.OnPressed += _ => OnGenerateNumber?.Invoke();
        WriteCardButton.OnPressed += _ =>
            OnWriteCard?.Invoke(IssueNameLine.Text, IssueSurnameLine.Text, IssueNumberLine.Text);
        ApplyLpButton.OnPressed += _ => TryApplySelectedLp();

        RecordsList.OnItemSelected += args =>
        {
            if (_suppressSelectionEvents)
                return;

            if (args.ItemIndex < 0 || args.ItemIndex >= _records.Count)
                return;

            OnSelectRecord?.Invoke(_records[args.ItemIndex].CardUid);
        };
    }

    public void UpdateState(CIDTabletBoundUiState state)
    {
        InfoNameLabel.Text = $"Имя: {state.Name}";
        InfoSurnameLabel.Text = $"Фамилия: {state.Surname}";
        InfoNumberLabel.Text = $"Номер гражданина: {state.CNumber}";
        InfoLpLabel.Text = $"LP: {state.LPCount}";
        InfoJobLabel.Text = $"Должность: {state.Job}";

        Tabs.SetTabVisible(2, state.CanIssue);
        IssueStatusLabel.Text = state.HasIssueCard
            ? "Карта для выдачи вставлена"
            : "Вставьте пустую CID карту в слот выдачи";

        if (!string.IsNullOrWhiteSpace(state.GeneratedNumber))
            IssueNumberLine.Text = state.GeneratedNumber;

        UpdateRecords(state.Records);
        UpdateSelectedRecord(state.SelectedRecord, state.CanViewDetails);
    }

    private void UpdateRecords(List<CIDDatabaseRecord> records)
    {
        _records = records;
        _suppressSelectionEvents = true;
        RecordsList.Clear();
        var selectedIndex = -1;
        for (var i = 0; i < records.Count; i++)
        {
            var record = records[i];
            RecordsList.AddItem($"{record.Name} {record.Surname} [{record.CNumber}]");

            if (_selectedRecord != null && _selectedRecord.CardUid == record.CardUid)
                selectedIndex = i;
        }

        if (selectedIndex >= 0)
            RecordsList.Select(selectedIndex);

        _suppressSelectionEvents = false;
    }

    private void UpdateSelectedRecord(CIDRecordDetails? details, bool canViewDetails)
    {
        _selectedRecord = details;

        SelectedNameLabel.Text = $"Имя: {details?.Name ?? "-"}";
        SelectedSurnameLabel.Text = $"Фамилия: {details?.Surname ?? "-"}";
        SelectedNumberLabel.Text = $"Номер: {details?.CNumber ?? "-"}";
        SelectedLevelLabel.Text = $"LP уровень: {(details?.LPLevel.ToString() ?? "-")}";
        SelectedTokensLabel.Text = $"Токены: {(details?.TokensCount.ToString() ?? "-")}";
        SelectedJobLabel.Text = $"Должность: {details?.Job ?? "-"}";
        SelectedAccessLabel.Text = $"Доступ: {(details?.Access.ToString() ?? "-")}";

        var canEditLp = canViewDetails && details != null;
        SelectedLpEdit.Editable = canEditLp;
        ApplyLpButton.Disabled = !canEditLp;

        if (details == null)
        {
            SelectedLpEdit.Text = string.Empty;
            return;
        }

        // Don't overwrite value while user is actively typing.
        if (!SelectedLpEdit.HasKeyboardFocus())
            SelectedLpEdit.Text = details.LPCount.ToString();
    }
    
    private void TryApplySelectedLp()
    {
        if (_selectedRecord == null)
            return;

        if (int.TryParse(SelectedLpEdit.Text, out var lp))
            OnChangeRecordLp?.Invoke(_selectedRecord.CardUid, lp);
    }
}
