using System.Linq;
using Content.Client.Humanoid;
using Content.Client.Message;
using Content.Client.Players.PlayTimeTracking;
using Content.Client.Sprite;
using Content.Shared.CCVar;
using Content.Shared.GameTicking;
using Content.Shared.HL2RP.CharacterPersistence;
using Content.Shared.Humanoid;
using Content.Shared.Humanoid.Markings;
using Content.Shared.Preferences;
using Content.Shared.Roles;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Player;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.Utility;
using Robust.Shared.Configuration;
using Robust.Shared.ContentPack;
using Robust.Shared.Enums;
using Robust.Shared.Prototypes;
using Direction = Robust.Shared.Maths.Direction;

namespace Content.Client.Lobby.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class HumanoidProfileEditor : BoxContainer
    {
        private readonly IClientPreferencesManager _preferencesManager;
        private readonly IConfigurationManager _cfgManager;
        private readonly IEntityManager _entManager;
        private readonly IFileDialogManager _dialogManager;
        private readonly IPlayerManager _playerManager;
        private readonly IPrototypeManager _prototypeManager;
        private readonly IResourceManager _resManager;
        private readonly MarkingManager _markingManager;
        private readonly JobRequirementsManager _requirements;
        private readonly LobbyUIController _controller;

        private readonly SpriteSystem _sprite;

        // CCvar.
        private int _maxNameLength;

        /// <summary>
        /// If we're attempting to save.
        /// </summary>
        public event Action? Save;

        /// <summary>
        /// The character slot for the current profile.
        /// </summary>
        public int? CharacterSlot;

        /// <summary>
        /// The work in progress profile being edited.
        /// </summary>
        public HumanoidCharacterProfile? Profile;

        private Direction _previewRotation = Direction.North;

        private bool _isDirty;

        public bool IsDirty
        {
            get => _isDirty;
            set
            {
                if (_isDirty == value)
                    return;

                _isDirty = value;
                UpdateSaveButton();
            }
        }

        // HL2RP CHANGE START profile-lock-ui
        private bool IsProfileLocked()
        {
            if (Profile == null || CharacterSlot == null)
                return false;

            var prefs = _preferencesManager.Preferences;
            return prefs != null && prefs.Characters.ContainsKey(CharacterSlot.Value);
        }

        private void UpdateProfileLockState()
        {
            var locked = IsProfileLocked();
            ProfileLockNoticeLabel.Visible = locked;
            ProfileLockNoticeLabel.SetMarkup(locked
                ? "[color=gray]Этот персонаж уже сохранен и заблокирован: редактирование и смена роли отключены.[/color]"
                : string.Empty);

            NameEdit.Editable = !locked;
            AgeEdit.Editable = !locked;
            RandomizeEverythingButton.Disabled = locked;
            NameRandomize.Disabled = locked;
            ImportButton.Disabled = locked;
            TabContainer.MouseFilter = locked ? MouseFilterMode.Stop : MouseFilterMode.Pass;

            // HL2RP role buttons
            Hl2RpRoleCivilian.Disabled = locked;
            Hl2RpRoleLoyalist.Disabled = locked;
            Hl2RpRoleVortigauntSlave.Disabled = locked;
            Hl2RpRoleCivilDefense.Disabled = locked;
            Hl2RpRoleCwuWorker.Disabled = locked;
            Hl2RpCivilDefenseRCT.Disabled = locked;
            Hl2RpCivilDefenseI5.Disabled = locked;
            Hl2RpCivilDefenseI4.Disabled = locked;
            Hl2RpCivilDefenseI3.Disabled = locked;
            Hl2RpCivilDefenseI2.Disabled = locked;
            Hl2RpCivilDefenseI1.Disabled = locked;
            Hl2RpCivilDefenseOFC.Disabled = locked;
            Hl2RpRoleCityAdministrator.Disabled = locked;
            Hl2RpRoleAdministratorSecretary.Disabled = locked;
            Hl2RpRoleCwuHead.Disabled = locked;
            Hl2RpRoleCivilDefenseSectorCommander.Disabled = locked;
            Hl2RpRoleCivilDefenseDispatcher.Disabled = locked;
            Hl2RpRoleResistanceCoordinator.Disabled = locked;
            Hl2RpRoleRebel.Disabled = locked;
            Hl2RpRoleVortigauntFree.Disabled = locked;
        }
        // HL2RP CHANGE END profile-lock-ui

        private ISawmill _sawmill;

        private MarkingsViewModel _markingsModel = new();

        public HumanoidProfileEditor(
            IClientPreferencesManager preferencesManager,
            IConfigurationManager configurationManager,
            IEntityManager entManager,
            IFileDialogManager dialogManager,
            ILogManager logManager,
            IPlayerManager playerManager,
            IPrototypeManager prototypeManager,
            IResourceManager resManager,
            JobRequirementsManager requirements,
            MarkingManager markings)
        {
            RobustXamlLoader.Load(this);
            _sawmill = logManager.GetSawmill("profile.editor");
            _cfgManager = configurationManager;
            _entManager = entManager;
            _dialogManager = dialogManager;
            _playerManager = playerManager;
            _prototypeManager = prototypeManager;
            _markingManager = markings;
            _preferencesManager = preferencesManager;
            _resManager = resManager;
            _requirements = requirements;
            _controller = UserInterfaceManager.GetUIController<LobbyUIController>();
            _sprite = _entManager.System<SpriteSystem>();

            _maxNameLength = _cfgManager.GetCVar(CCVars.MaxNameLength);
            _allowFlavorText = _cfgManager.GetCVar(CCVars.FlavorText);

            Markings.SetModel(_markingsModel);

            SetupHl2RpTab();
            // Hide the legacy job priorities tab. HL2RP uses the dedicated HL2RP role tab.
            TabContainer.SetTabVisible(2, false);
            // Hide Antags tab for HL2RP flow.
            TabContainer.SetTabVisible(3, false);

            ImportButton.OnPressed += args =>
            {
                ImportProfile();
            };

            ExportButton.OnPressed += args =>
            {
                ExportProfile();
            };

            ExportImageButton.OnPressed += args =>
            {
                ExportImage();
            };

            OpenImagesButton.OnPressed += args =>
            {
                _resManager.UserData.OpenOsWindow(ContentSpriteSystem.Exports);
            };

            ResetButton.OnPressed += args =>
            {
                SetProfile((HumanoidCharacterProfile?)_preferencesManager.Preferences?.SelectedCharacter, _preferencesManager.Preferences?.SelectedCharacterIndex);
            };

            SaveButton.OnPressed += args =>
            {
                Save?.Invoke();
            };

            #region Left

            #region Name

            NameEdit.OnTextChanged += args => { SetName(args.Text); };
            NameEdit.IsValid = args => args.Length <= _maxNameLength;
            NameRandomize.OnPressed += args => RandomizeName();
            RandomizeEverythingButton.OnPressed += args => { RandomizeEverything(); };
            WarningLabel.SetMarkup($"[color=red]{Loc.GetString("humanoid-profile-editor-naming-rules-warning")}[/color]");

            #endregion Name

            #region Appearance

            TabContainer.SetTabTitle(0, "HL2RP");
            TabContainer.SetTabTitle(1, Loc.GetString("humanoid-profile-editor-appearance-tab"));

            #region Sex

            SexButton.OnItemSelected += args =>
            {
                SexButton.SelectId(args.Id);
                SetSex((Sex)args.Id);
            };

            #endregion Sex

            #region Age

            AgeEdit.OnTextChanged += args =>
            {
                if (!int.TryParse(args.Text, out var newAge))
                    return;

                SetAge(newAge);
            };

            #endregion Age

            #region Gender

            PronounsButton.AddItem(Loc.GetString("humanoid-profile-editor-pronouns-male-text"), (int)Gender.Male);
            PronounsButton.AddItem(Loc.GetString("humanoid-profile-editor-pronouns-female-text"), (int)Gender.Female);
            PronounsButton.AddItem(Loc.GetString("humanoid-profile-editor-pronouns-epicene-text"), (int)Gender.Epicene);
            PronounsButton.AddItem(Loc.GetString("humanoid-profile-editor-pronouns-neuter-text"), (int)Gender.Neuter);

            PronounsButton.OnItemSelected += args =>
            {
                PronounsButton.SelectId(args.Id);
                SetGender((Gender)args.Id);
            };

            #endregion Gender

            RefreshSpecies();

            SpeciesButton.OnItemSelected += args =>
            {
                SpeciesButton.SelectId(args.Id);
                SetSpecies(_species[args.Id].ID);
                OnSkinColorOnValueChanged();
            };

            #region Skin

            Skin.OnValueChanged += _ =>
            {
                OnSkinColorOnValueChanged();
            };

            RgbSkinColorContainer.AddChild(_rgbSkinColorSelector = new ColorSelectorSliders());
            _rgbSkinColorSelector.SelectorType = ColorSelectorSliders.ColorSelectorType.Hsv; // defaults color selector to HSV
            _rgbSkinColorSelector.OnColorChanged += _ =>
            {
                OnSkinColorOnValueChanged();
            };

            #endregion

            #region SpawnPriority

            foreach (var value in Enum.GetValues<SpawnPriorityPreference>())
            {
                SpawnPriorityButton.AddItem(Loc.GetString($"humanoid-profile-editor-preference-spawn-priority-{value.ToString().ToLower()}"), (int)value);
            }

            SpawnPriorityButton.OnItemSelected += args =>
            {
                SpawnPriorityButton.SelectId(args.Id);
                SetSpawnPriority((SpawnPriorityPreference)args.Id);
            };

            #endregion SpawnPriority

            #region Eyes

            EyeColorPicker.OnEyeColorPicked += newColor =>
            {
                if (Profile is null)
                    return;
                Profile = Profile.WithCharacterAppearance(
                    Profile.Appearance.WithEyeColor(newColor));
                _markingsModel.SetOrganEyeColor(Profile.Appearance.EyeColor);
                ReloadProfilePreview();
            };

            #endregion Eyes

            #endregion Appearance

            #region Jobs

            TabContainer.SetTabTitle(2, Loc.GetString("humanoid-profile-editor-jobs-tab"));

            PreferenceUnavailableButton.AddItem(
                Loc.GetString("humanoid-profile-editor-preference-unavailable-stay-in-lobby-button"),
                (int)PreferenceUnavailableMode.StayInLobby);
            PreferenceUnavailableButton.AddItem(
                Loc.GetString("humanoid-profile-editor-preference-unavailable-spawn-as-overflow-button",
                              ("overflowJob", Loc.GetString(SharedGameTicker.FallbackOverflowJobName))),
                (int)PreferenceUnavailableMode.SpawnAsOverflow);

            PreferenceUnavailableButton.OnItemSelected += args =>
            {
                PreferenceUnavailableButton.SelectId(args.Id);
                Profile = Profile?.WithPreferenceUnavailable((PreferenceUnavailableMode)args.Id);
                SetDirty();
            };

            _jobCategories = new Dictionary<string, BoxContainer>();

            RefreshAntags();
            RefreshJobs();

            #endregion Jobs

            TabContainer.SetTabTitle(3, Loc.GetString("humanoid-profile-editor-antags-tab"));

            RefreshTraits();

            TabContainer.SetTabTitle(4, Loc.GetString("humanoid-profile-editor-traits-tab")); // Corvax-TTS-Edit

            #region Markings

            TabContainer.SetTabTitle(5, Loc.GetString("humanoid-profile-editor-markings-tab"));

            _markingsModel.MarkingsChanged += (_, _) => OnMarkingChange();
            _markingsModel.MarkingsReset += OnMarkingChange;

            #endregion Markings

            RefreshFlavorText();

            RefreshVoiceTab(); // Corvax-TTS

            #region Dummy

            SpriteRotateLeft.OnPressed += _ =>
            {
                _previewRotation = _previewRotation.TurnCw();
                SetPreviewRotation(_previewRotation);
            };
            SpriteRotateRight.OnPressed += _ =>
            {
                _previewRotation = _previewRotation.TurnCcw();
                SetPreviewRotation(_previewRotation);
            };

            #endregion Dummy

            #endregion Left

            ShowClothes.OnToggled += args =>
            {
                ReloadPreview();
            };

            SpeciesInfoButton.OnPressed += OnSpeciesInfoButtonPressed;

            UpdateSpeciesGuidebookIcon();
            IsDirty = false;
        }

        private void Hl2RpSetRole(string jobId)
        {
            if (Profile == null)
                return;

            if (IsProfileLocked())
                return;

            Profile = Profile.WithJobPriority(jobId, JobPriority.High);
            JobOverride = _prototypeManager.TryIndex<JobPrototype>(jobId, out var job) ? job : null;
            ReloadPreview();
            UpdateJobPriorities();
            UpdateHl2RpSelection();
            SetDirty();
        }

        private void UpdateHl2RpSelection()
        {
            if (Profile == null)
                return;

            var selectedHigh = Profile.JobPriorities.FirstOrDefault(p => p.Value == JobPriority.High).Key;
            var selected = selectedHigh.Id;

            // reset all toggles
            Hl2RpRoleCivilian.Pressed = false;
            Hl2RpRoleLoyalist.Pressed = false;
            Hl2RpRoleVortigauntSlave.Pressed = false;
            Hl2RpRoleCivilDefense.Pressed = false;
            Hl2RpRoleCwuWorker.Pressed = false;
            Hl2RpCivilDefenseRCT.Pressed = false;
            Hl2RpCivilDefenseI5.Pressed = false;
            Hl2RpCivilDefenseI4.Pressed = false;
            Hl2RpCivilDefenseI3.Pressed = false;
            Hl2RpCivilDefenseI2.Pressed = false;
            Hl2RpCivilDefenseI1.Pressed = false;
            Hl2RpCivilDefenseOFC.Pressed = false;
            Hl2RpRoleCityAdministrator.Pressed = false;
            Hl2RpRoleAdministratorSecretary.Pressed = false;
            Hl2RpRoleCwuHead.Pressed = false;
            Hl2RpRoleCivilDefenseSectorCommander.Pressed = false;
            Hl2RpRoleCivilDefenseDispatcher.Pressed = false;
            Hl2RpRoleResistanceCoordinator.Pressed = false;
            Hl2RpRoleRebel.Pressed = false;
            Hl2RpRoleVortigauntFree.Pressed = false;

            if (string.IsNullOrWhiteSpace(selected))
                return;

            switch (selected)
            {
                case "Civilian":
                    Hl2RpRoleCivilian.Pressed = true;
                    break;
                case "Loyalist":
                    Hl2RpRoleLoyalist.Pressed = true;
                    break;
                case "VortigauntSlave":
                    Hl2RpRoleVortigauntSlave.Pressed = true;
                    break;
                case "CWUWorker":
                    Hl2RpRoleCwuWorker.Pressed = true;
                    break;
                case "CityAdministrator":
                    Hl2RpRoleCityAdministrator.Pressed = true;
                    break;
                case "AdministratorSecretary":
                    Hl2RpRoleAdministratorSecretary.Pressed = true;
                    break;
                case "CWUHead":
                    Hl2RpRoleCwuHead.Pressed = true;
                    break;
                case "CivilDefenseSectorCommander":
                    Hl2RpRoleCivilDefenseSectorCommander.Pressed = true;
                    break;
                case "CivilDefenseDispatcher":
                    Hl2RpRoleCivilDefenseDispatcher.Pressed = true;
                    break;
                case "ResistanceCoordinator":
                    Hl2RpRoleResistanceCoordinator.Pressed = true;
                    break;
                case "Rebel":
                    Hl2RpRoleRebel.Pressed = true;
                    break;
                case "VortigauntFree":
                    Hl2RpRoleVortigauntFree.Pressed = true;
                    break;

                // Civil Defense: we can't infer exact rank yet (future system),
                // but we still highlight the group and show rank buttons.
                case "CivilDefenseRecruit":
                case "CivilDefenseOfficer":
                case "CivilDefenseUnit":
                    Hl2RpRoleCivilDefense.Pressed = true;
                    Hl2RpCivilDefenseRanks.Visible = true;
                    break;
            }
        }

        private void SetupHl2RpTab()
        {
            Hl2RpRoleCivilDefense.OnPressed += _ =>
            {
                Hl2RpCivilDefenseRanks.Visible = !Hl2RpCivilDefenseRanks.Visible;
            };

            Hl2RpRoleCivilian.OnPressed += _ => Hl2RpSetRole("Civilian");
            Hl2RpRoleLoyalist.OnPressed += _ => Hl2RpSetRole("Loyalist");
            Hl2RpRoleVortigauntSlave.OnPressed += _ => Hl2RpSetRole("VortigauntSlave");
            Hl2RpRoleCwuWorker.OnPressed += _ => Hl2RpSetRole("CWUWorker");

            // GO ranks for future systems: currently all map to the same job preference.
            Hl2RpCivilDefenseRCT.OnPressed += _ => Hl2RpSetRole("CivilDefenseRecruit");
            Hl2RpCivilDefenseI5.OnPressed += _ => Hl2RpSetRole("CivilDefenseOfficer");
            Hl2RpCivilDefenseI4.OnPressed += _ => Hl2RpSetRole("CivilDefenseOfficer");
            Hl2RpCivilDefenseI3.OnPressed += _ => Hl2RpSetRole("CivilDefenseUnit");
            Hl2RpCivilDefenseI2.OnPressed += _ => Hl2RpSetRole("CivilDefenseUnit");
            Hl2RpCivilDefenseI1.OnPressed += _ => Hl2RpSetRole("CivilDefenseUnit");
            Hl2RpCivilDefenseOFC.OnPressed += _ => Hl2RpSetRole("CivilDefenseOfficer");

            Hl2RpRoleCityAdministrator.OnPressed += _ => Hl2RpSetRole("CityAdministrator");
            Hl2RpRoleAdministratorSecretary.OnPressed += _ => Hl2RpSetRole("AdministratorSecretary");
            Hl2RpRoleCwuHead.OnPressed += _ => Hl2RpSetRole("CWUHead");
            Hl2RpRoleCivilDefenseSectorCommander.OnPressed += _ => Hl2RpSetRole("CivilDefenseSectorCommander");
            Hl2RpRoleCivilDefenseDispatcher.OnPressed += _ => Hl2RpSetRole("CivilDefenseDispatcher");

            Hl2RpRoleResistanceCoordinator.OnPressed += _ => Hl2RpSetRole("ResistanceCoordinator");
            Hl2RpRoleRebel.OnPressed += _ => Hl2RpSetRole("Rebel");
            Hl2RpRoleVortigauntFree.OnPressed += _ => Hl2RpSetRole("VortigauntFree");
        }

        private void SetDirty()
        {
            // Locked profiles are immutable in HL2RP flow: never prompt to save.
            if (IsProfileLocked())
            {
                IsDirty = false;
                return;
            }

            // If it equals default then reset the button.
            if (Profile == null || _preferencesManager.Preferences?.SelectedCharacter.MemberwiseEquals(Profile) == true)
            {
                IsDirty = false;
                return;
            }

            // TODO: Check if profile matches default.
            IsDirty = true;
        }

        /// <summary>
        /// Reloads the entire dummy entity for preview.
        /// </summary>
        /// <remarks>
        /// This is expensive so not recommended to run if you have a slider.
        /// </remarks>
        private void ReloadPreview()
        {
            if (Profile == null)
                return;

            CharacterInventoryPreviewData? preview = null;
            if (CharacterSlot is { } slot)
                preview = _preferencesManager.GetCharacterInventoryPreview(slot);

            SpriteView.LoadPreview(Profile, JobOverride, ShowClothes.Pressed, preview);

            // Check and set the dirty flag to enable the save/reset buttons as appropriate.
            SetDirty();
        }

        /// <summary>
        /// Resets the profile to the defaults.
        /// </summary>
        public void ResetToDefault()
        {
            SetProfile(
                (HumanoidCharacterProfile?)_preferencesManager.Preferences?.SelectedCharacter,
                _preferencesManager.Preferences?.SelectedCharacterIndex);
        }

        /// <summary>
        /// Sets the editor to the specified profile with the specified slot.
        /// </summary>
        public void SetProfile(HumanoidCharacterProfile? profile, int? slot)
        {
            Profile = profile?.Clone();
            CharacterSlot = slot;
            IsDirty = false;
            JobOverride = null;

            UpdateNameEdit();
            UpdateFlavorTextEdit();
            UpdateSexControls();
            UpdateGenderControls();
            UpdateSkinColor();
            UpdateSpawnPriorityControls();
            UpdateAgeEdit();
            UpdateEyePickers();
            UpdateSaveButton();
            UpdateMarkings();
            UpdateTTSVoicesControls(); // Corvax-TTS
            // HL2RP CHANGE START profile-lock-ui
            UpdateProfileLockState();
            // HL2RP CHANGE END profile-lock-ui

            RefreshAntags();
            RefreshJobs();
            RefreshLoadouts();
            RefreshSpecies();
            RefreshTraits();
            RefreshFlavorText();
            ReloadPreview();
            UpdateHl2RpSelection();

            if (Profile != null)
            {
                PreferenceUnavailableButton.SelectId((int)Profile.PreferenceUnavailable);
            }
        }

        /// <summary>
        /// A slim reload that only updates the entity itself and not any of the job entities, etc.
        /// </summary>
        private void ReloadProfilePreview()
        {
            if (Profile == null)
                return;

            SpriteView.ReloadProfilePreview(Profile);

            // Check and set the dirty flag to enable the save/reset buttons as appropriate.
            SetDirty();
        }

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
            if (!disposing)
                return;

            _loadoutWindow?.Dispose();
            _loadoutWindow = null;
        }

        protected override void EnteredTree()
        {
            base.EnteredTree();
            ReloadPreview();
        }

        private void UpdateSaveButton()
        {
            // HL2RP CHANGE START profile-lock-ui
            var locked = IsProfileLocked();
            SaveButton.Disabled = Profile is null || !IsDirty || locked;
            ResetButton.Disabled = Profile is null || !IsDirty || locked;
            SaveButton.ToolTip = locked ? "Персонаж заблокирован после первого сохранения." : null;
            ResetButton.ToolTip = locked ? "Персонаж заблокирован после первого сохранения." : null;
            // HL2RP CHANGE END profile-lock-ui
        }

        private void SetPreviewRotation(Direction direction)
        {
            SpriteView.OverrideDirection = (Direction)((int)direction % 4 * 2);
        }
    }
}
