- type: job
  id: CityAdministrator
  name: job-name-city-administrator
  description: job-description-city-administrator
  playTimeTracker: JobCityAdministrator
  setPreference: true
  canBeAntag: false
  supervisors: job-supervisors-everyone
  cidCardSpawn:
    lpCount: 0
    tabletPermissions: None
    job: "городской администратор"

- type: job
  id: AdministratorSecretary
  name: job-name-administrator-secretary
  description: job-description-administrator-secretary
  playTimeTracker: JobAdministratorSecretary
  setPreference: true
  canBeAntag: false
  supervisors: job-supervisors-everyone
  cidCardSpawn:
    lpCount: 0
    tabletPermissions: None
    job: "секретарь администратора"

- type: job
  id: CWUHead
  name: job-name-cwu-head
  description: job-description-cwu-head
  playTimeTracker: JobCWUHead
  setPreference: true
  canBeAntag: false
  supervisors: job-supervisors-everyone
  cidCardSpawn:
    lpCount: 0
    tabletPermissions: None
    job: "глава ГСР"

- type: job
  id: CWUWorker
  name: job-name-cwu-worker
  description: job-description-cwu-worker
  playTimeTracker: JobCWUWorker
  setPreference: true
  canBeAntag: false
  supervisors: job-supervisors-everyone
  cidCardSpawn:
    lpCount: 0
    tabletPermissions: None
    job: "работник ГСР"

- type: job
  id: CivilDefenseSectorCommander
  name: job-name-civil-defense-sector-commander
  description: job-description-civil-defense-sector-commander
  playTimeTracker: JobCivilDefenseSectorCommander
  setPreference: true
  canBeAntag: false
  supervisors: job-supervisors-everyone
  cidCardSpawn:
    lpCount: 0
    tabletPermissions: None
    job: "секторный командир"

- type: job
  id: CivilDefenseDispatcher
  name: job-name-civil-defense-dispatcher
  description: job-description-civil-defense-dispatcher
  playTimeTracker: JobCivilDefenseDispatcher
  setPreference: true
  canBeAntag: false
  supervisors: job-supervisors-everyone
  cidCardSpawn:
    lpCount: 0
    tabletPermissions: None
    job: "диспетчер"

- type: job
  id: CivilDefenseOfficer
  name: job-name-civil-defense-officer
  description: job-description-civil-defense-officer
  playTimeTracker: JobCivilDefenseOfficer
  setPreference: true
  canBeAntag: false
  supervisors: job-supervisors-everyone
  cidCardSpawn:
    lpCount: 0
    tabletPermissions: None
    job: "офицер ГО"

- type: job
  id: CivilDefenseUnit
  name: job-name-civil-defense-unit
  description: job-description-civil-defense-unit
  playTimeTracker: JobCivilDefenseUnit
  setPreference: true
  canBeAntag: false
  supervisors: job-supervisors-everyone
  cidCardSpawn:
    lpCount: 0
    tabletPermissions: None
    job: "юнит ГО"

- type: job
  id: CivilDefenseRecruit
  name: job-name-civil-defense-recruit
  description: job-description-civil-defense-recruit
  playTimeTracker: JobCivilDefenseRecruit
  setPreference: true
  canBeAntag: false
  supervisors: job-supervisors-everyone
  cidCardSpawn:
    lpCount: 0
    tabletPermissions: None
    job: "рекрут ГО"

- type: job
  id: Loyalist
  name: job-name-loyalist
  description: job-description-loyalist
  playTimeTracker: JobLoyalist
  setPreference: true
  canBeAntag: false
  supervisors: job-supervisors-everyone
  cidCardSpawn:
    lpCount: 0
    tabletPermissions: None
    job: "лоялист"

- type: job
  id: Civilian
  name: job-name-civilian
  description: job-description-civilian
  playTimeTracker: JobCivilian
  setPreference: true
  canBeAntag: false
  supervisors: job-supervisors-everyone
  cidCardSpawn:
    lpCount: 0
    tabletPermissions: None
    job: "гражданский"

- type: job
  id: VortigauntSlave
  name: job-name-vortigaunt-slave
  description: job-description-vortigaunt-slave
  playTimeTracker: JobVortigauntSlave
  setPreference: true
  canBeAntag: false
  supervisors: job-supervisors-everyone
  cidCardSpawn:
    lpCount: 0
    tabletPermissions: None
    job: "вортигонт-раб"

- type: job
  id: ResistanceCoordinator
  name: job-name-resistance-coordinator
  description: job-description-resistance-coordinator
  playTimeTracker: JobResistanceCoordinator
  setPreference: true
  canBeAntag: false
  supervisors: job-supervisors-everyone
  cidCardSpawn:
    lpCount: 0
    tabletPermissions: None
    job: "координатор сопротивления"

- type: job
  id: Rebel
  name: job-name-rebel
  description: job-description-rebel
  playTimeTracker: JobRebel
  setPreference: true
  canBeAntag: false
  supervisors: job-supervisors-everyone
  cidCardSpawn:
    lpCount: 0
    tabletPermissions: None
    job: "повстанец"

- type: job
  id: VortigauntFree
  name: job-name-vortigaunt-free
  description: job-description-vortigaunt-free
  playTimeTracker: JobVortigauntFree
  setPreference: true
  canBeAntag: false
  supervisors: job-supervisors-everyone
  cidCardSpawn:
    lpCount: 0
    tabletPermissions: None
    job: "вортигонт свободный"
