- type: antag
  id: Thief
  name: roles-antag-thief-name
  antagonist: true
  setPreference: false
  objective: roles-antag-thief-objective
  guides: [ Thieves ]
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 30h # Corvax-RoleTime 1

- type: startingGear
  id: ThiefGear
  storage:
    back:
    - ThiefBeacon
    - SatchelThief
